---
title: "Visualizing Images with R"
output: html_document
---

This notebook will show you how to visualize the images from the Fashion MNIST dataset that are stored in tabular format.

```{r}
# load the data
data = read.csv("fashion-mnist_train.csv")
```

This code will visualize one image.

```{r}
# get one image in row format (will use the first row, remove first column with label)
im_row_format = data.matrix(data[1,-1])
# convert to 28x28 matrix (dimensions of the image)
im_matrix_format = matrix(im_row_format, ncol=28, nrow=28)
# flip upside down (needed for correct viz)
im_matrix_format_flip = im_matrix_format[, ncol(im_matrix_format):1]
# visualize (divide by 255 to go from 0-255 pixel range to 0-1 pixel range, remove axes from plot, set the color sequence to be gray from 0 to 1 with 256 intermediate values, just like the original pixel scale)
image(im_matrix_format_flip / 255, axes=FALSE, col = grey(seq(0, 1, length = 256)), asp=1)
```

This code will visualize a group of images.

```{r}
# visualize a group of image (will do the first three)
num_ims = 3
# set up an empty image bank to store the states (3 * 28 rows will become 3 * 28 columns during viz)
image_bank = matrix(0, nrow = 28 * num_ims, ncol = 28)

# loop over the first three rows and store images in bank
for(i in 1:3){
  im_row_format = data.matrix(data[i,-1])
  im_matrix_format = matrix(im_row_format, ncol=28, nrow=28)
  im_matrix_format_flip = im_matrix_format[, ncol(im_matrix_format):1]
  image_bank[((i-1)*28 + 1):(i * 28),] = im_matrix_format_flip
}
# visualize (set aspect to be 1/num_ims to get square plot for each image)
image(image_bank / 255, axes=FALSE, col = grey(seq(0, 1, length = 256)), asp=1 / num_ims)
```